identidock:
  build: .
  ports:
    - "5000:5000"
  environment:
    ENV: DEV
  links:
    - dnmonster
    - redis
  volumes:
    - ./app:/app
    
dnmonster:
  image: amouat/dnmonster:1.0
redis:  
  image: redis:3.0
